{% set name = "plotly" %}
{% set version = "5.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ea91a56571292ade3e3bc9bf712eba0b95a1fb0a941375d978cc79432e055f4

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=40.8.0
    - wheel
  run:
    - python
    - packaging
    - tenacity >=6.2.0
  run_constrained:
    - jupyterlab >=3
    - ipywidgets >=7.6

test:
  imports:
    - jupyterlab_plotly
    - plotly
    - plotly.offline
    - plotly.io
    - plotly.data
    - plotly.colors
    - plotly.graph_objects
    - _plotly_utils
    - _plotly_utils.colors
    - _plotly_future_
    - plotly.graph_objs.bar
    - plotly.graph_objs.barpolar
    - plotly.graph_objs.box
    - plotly.graph_objs.candlestick
    - plotly.graph_objs.carpet
    - plotly.graph_objs.choropleth
    - plotly.graph_objs.choroplethmapbox
    - plotly.graph_objs.cone
    - plotly.graph_objs.contour
    - plotly.graph_objs.contourcarpet
    - plotly.graph_objs.densitymapbox
    - plotly.graph_objs.funnel
    - plotly.graph_objs.funnelarea
    - plotly.graph_objs.heatmap
    - plotly.graph_objs.heatmapgl
    - plotly.graph_objs.histogram
    - plotly.graph_objs.histogram2d
    - plotly.graph_objs.histogram2dcontour
    - plotly.graph_objs.icicle
    - plotly.graph_objs.image
    - plotly.graph_objs.indicator
    - plotly.graph_objs.isosurface
    - plotly.graph_objs.layout
    - plotly.graph_objs.mesh3d
    - plotly.graph_objs.ohlc
    - plotly.graph_objs.parcats
    - plotly.graph_objs.parcoords
    - plotly.graph_objs.pie
    - plotly.graph_objs.pointcloud
    - plotly.graph_objs.sankey
    - plotly.graph_objs.scatter
    - plotly.graph_objs.scatter3d
    - plotly.graph_objs.scattercarpet
    - plotly.graph_objs.scattergeo
    - plotly.graph_objs.scattergl
    - plotly.graph_objs.scattermapbox
    - plotly.graph_objs.scatterpolar
    - plotly.graph_objs.scatterpolargl
    - plotly.graph_objs.scatterternary
    - plotly.graph_objs.splom
    - plotly.graph_objs.streamtube
    - plotly.graph_objs.sunburst
    - plotly.graph_objs.surface
    - plotly.graph_objs.table
    - plotly.graph_objs.treemap
    - plotly.graph_objs.violin
    - plotly.graph_objs.volume
    - plotly.graph_objs.waterfall
    - plotly.validators
    - plotly.validators.bar
    - plotly.validators.barpolar
    - plotly.validators.box
    - plotly.validators.candlestick
    - plotly.validators.carpet
    - plotly.validators.choropleth
    - plotly.validators.choroplethmapbox
    - plotly.validators.cone
    - plotly.validators.contour
    - plotly.validators.contourcarpet
    - plotly.validators.densitymapbox
    - plotly.validators.frame
    - plotly.validators.funnel
    - plotly.validators.funnelarea
    - plotly.validators.heatmap
    - plotly.validators.heatmapgl
    - plotly.validators.histogram
    - plotly.validators.histogram2d
    - plotly.validators.histogram2dcontour
    - plotly.validators.icicle
    - plotly.validators.image
    - plotly.validators.indicator
    - plotly.validators.isosurface
    - plotly.validators.layout
    - plotly.validators.mesh3d
    - plotly.validators.ohlc
    - plotly.validators.parcats
    - plotly.validators.parcoords
    - plotly.validators.pie
    - plotly.validators.pointcloud
    - plotly.validators.sankey
    - plotly.validators.scatter
    - plotly.validators.scatter3d
    - plotly.validators.scattercarpet
    - plotly.validators.scattergeo
    - plotly.validators.scattergl
    - plotly.validators.scattermapbox
    - plotly.validators.scatterpolar
    - plotly.validators.scatterpolargl
    - plotly.validators.scatterternary
    - plotly.validators.splom
    - plotly.validators.streamtube
    - plotly.validators.sunburst
    - plotly.validators.surface
    - plotly.validators.table
    - plotly.validators.treemap
    - plotly.validators.violin
    - plotly.validators.volume
    - plotly.validators.waterfall
  requires:
    - pip
    - {{ pin_compatible("numpy") }}
    - matplotlib-base
    - pandas
  commands:
    - pip check
    # test imports requiring matplotlib
    - python -c "import plotly.matplotlylib; import plotly.matplotlylib.mplexporter; import plotly.matplotlylib.mplexporter.renderers"
    # test imports requiring numpy
    - python -c "import plotly.figure_factory"
    # test imports requiring pandas
    - python -c "import plotly.express; import plotly.express.data; import plotly.express.colors; import plotly.express.trendline_functions"

about:
  home: https://plotly.com/python
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: An interactive JavaScript-based visualization library for Python
  description: |
    plotly.py is an interactive, open-source, and JavaScript-based graphing
    library for Python. Built on top of plotly.js, plotly.py is a high-level,
    declarative charting library that includes over 30 chart types,
    including scientific charts, 3D graphs, statistical charts, SVG maps,
    financial charts, and more.
  doc_url: https://plotly.com/python
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - chohner
    - moorepants
    - ocefpaf
