{% set version = "2.0.0" %}
{% set sha256 = "eede6581abe00f319909fa84e99f6033b9e735427fb64b570dfbc312fc0dd771" %}
{% set pkg_name = "plotly" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: plotly-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - requests
    - pytz
    - six

test:
  imports:
    - plotly

about:
  home: https://plot.ly/python/
  license: MIT
  summary: 'An interactive, browser-based graphing library for Python'
  description: |
    Plotly's Python graphing library makes interactive,
    publication-quality graphs online. Examples of how to make line
    plots, scatter plots, area charts, bar charts, error bars, box plots,
    histograms, heatmaps, subplots, multiple-axes, polar charts and
    bubble charts.
  doc_url: https://plot.ly/python/
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - chohner
