{% set version = "2.4.1" %}
{% set sha256 = "f588991dce15437debd825eca935c8cfbabf438cdc0dcd2ce7a88f429d982f69" %}
{% set pkg_name = "plotly" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: plotly-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - decorator >=4.0.6
    - nbformat >=4.2
    - pytz
    - requests
    - six
    - setuptools

test:
  imports:
    - plotly
    - plotly.api
    - plotly.api.v1
    - plotly.api.v2
    - plotly.dashboard_objs
    # Requires numpy (optional)
    #- plotly.figure_factory
    - plotly.graph_objs
    - plotly.grid_objs
    #- plotly.matplotlylib
    #- plotly.matplotlylib.mplexporter
    #- plotly.matplotlylib.mplexporter.renderers
    - plotly.offline
    - plotly.plotly
    - plotly.plotly.chunked_requests
    # Requires IPython (optional)
    #- plotly.widgets

about:
  home: https://plot.ly/python/
  license: MIT
  summary: 'An interactive, browser-based graphing library for Python'
  description: |
    Plotly's Python graphing library makes interactive,
    publication-quality graphs online. Examples of how to make line
    plots, scatter plots, area charts, bar charts, error bars, box plots,
    histograms, heatmaps, subplots, multiple-axes, polar charts and
    bubble charts.
  doc_url: https://plot.ly/python/
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - chohner
