{% set version = "3.0.1" %}
{% set sha256 = "5a51a52a2735f5974ffbed06e97f1591a18ef0d8a96ac90f6a1c1bb88c72504d" %}
{% set pkg_name = "plotly" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: plotly-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - requests
    - pytz
    - six
    - decorator >=4.0.6
    - nbformat >=4.2
    - retrying >=1.3.3

test:
  imports:
    - plotly

about:
  home: https://plot.ly/python/
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'An interactive, browser-based graphing library for Python'
  description: |
    Plotly's Python graphing library makes interactive,
    publication-quality graphs online. Examples of how to make line
    plots, scatter plots, area charts, bar charts, error bars, box plots,
    histograms, heatmaps, subplots, multiple-axes, polar charts and
    bubble charts.
  doc_url: https://plot.ly/python/
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - chohner
    - moorepants
