{% set version = "4.5.1" %}

package:
  name: plotly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/plotly/plotly-{{ version }}.tar.gz
  sha256: 75c95c0eacdeb260fd2dc21dbe8583721c3e229bdf176a41d11092f74171d8bc

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - retrying >=1.3.3
    - six

test:
  imports:
    - plotly

about:
  home: https://plot.ly/python/
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'An interactive, browser-based graphing library for Python'
  description: |
    Plotly's Python graphing library makes interactive,
    publication-quality graphs online. Examples of how to make line
    plots, scatter plots, area charts, bar charts, error bars, box plots,
    histograms, heatmaps, subplots, multiple-axes, polar charts and
    bubble charts.
  doc_url: https://plot.ly/python/
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - chohner
    - moorepants
    - ocefpaf
