{% set name = "plotly" %}
{% set version = "6.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8840a184d18ccae0f9189c2b9a2943923fd5cae7717b723f36eef78f444e5a73

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - plotly_get_chrome = plotly.io._kaleido:plotly_get_chrome
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools >=61
    - jupyter-packaging >=0.10.0,<0.11
  run:
    - python
    - packaging
    - narwhals >=1.15.1
  run_constrained:
    - kaleido >=1.0.0

test:
  imports:
    - plotly
    - plotly.offline
    - plotly.io
    - plotly.matplotlylib
    - plotly.matplotlylib.mplexporter
    - plotly.matplotlylib.mplexporter.renderers
    - plotly.figure_factory
    - plotly.data
    - plotly.colors
    - plotly.express
    - plotly.express.data
    - plotly.express.colors
    - plotly.express.trendline_functions
    - plotly.graph_objects
    - plotly.graph_objs
    - plotly.graph_objs.bar
    - plotly.graph_objs.barpolar
    - plotly.graph_objs.box
    - plotly.graph_objs.candlestick
    - plotly.graph_objs.carpet
    - plotly.graph_objs.choropleth
    - plotly.graph_objs.choroplethmap
    - plotly.graph_objs.choroplethmapbox
    - plotly.graph_objs.cone
    - plotly.graph_objs.contour
    - plotly.graph_objs.contourcarpet
    - plotly.graph_objs.densitymap
    - plotly.graph_objs.densitymapbox
    - plotly.graph_objs.funnel
    - plotly.graph_objs.funnelarea
    - plotly.graph_objs.heatmap
    - plotly.graph_objs.histogram
    - plotly.graph_objs.histogram2d
    - plotly.graph_objs.histogram2dcontour
    - plotly.graph_objs.icicle
    - plotly.graph_objs.image
    - plotly.graph_objs.indicator
    - plotly.graph_objs.isosurface
    - plotly.graph_objs.layout
    - plotly.graph_objs.mesh3d
    - plotly.graph_objs.ohlc
    - plotly.graph_objs.parcats
    - plotly.graph_objs.parcoords
    - plotly.graph_objs.pie
    - plotly.graph_objs.sankey
    - plotly.graph_objs.scatter
    - plotly.graph_objs.scatter3d
    - plotly.graph_objs.scattercarpet
    - plotly.graph_objs.scattergeo
    - plotly.graph_objs.scattergl
    - plotly.graph_objs.scattermap
    - plotly.graph_objs.scattermapbox
    - plotly.graph_objs.scatterpolar
    - plotly.graph_objs.scatterpolargl
    - plotly.graph_objs.scattersmith
    - plotly.graph_objs.scatterternary
    - plotly.graph_objs.splom
    - plotly.graph_objs.streamtube
    - plotly.graph_objs.sunburst
    - plotly.graph_objs.surface
    - plotly.graph_objs.table
    - plotly.graph_objs.treemap
    - plotly.graph_objs.violin
    - plotly.graph_objs.volume
    - plotly.graph_objs.waterfall
    - plotly.package_data
    - plotly.package_data.datasets
    - plotly.package_data.templates
    - plotly.validators
  requires:
    - pip
    - numpy
    - matplotlib-base
    - pandas
  commands:
    - pip check
    # needs kaleido >=1.0.0
    # - plotly_get_chrome --help

about:
  home: https://plotly.com/python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An interactive JavaScript-based visualization library for Python
  description: |
    plotly.py is an interactive, open-source, and JavaScript-based graphing
    library for Python. Built on top of plotly.js, plotly.py is a high-level,
    declarative charting library that includes over 30 chart types,
    including scientific charts, 3D graphs, statistical charts, SVG maps,
    financial charts, and more.
  doc_url: https://plotly.com/python
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - chohner
    - moorepants
    - ocefpaf
