{% set version = "5.1.0" %}

package:
  name: plotly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/plotly/plotly-{{ version }}.tar.gz
  sha256: 71f6744acdc524c22236c226d7cf1072d1a58ebacaf749c640998298472c8c44

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=40.8.0
    - wheel
    - jupyterlab >=3.0
  run:
    - python >=3.6
    # Dependencies for Core Plotly Functionality:
    # retrying requests
    - tenacity >=6.2.0
    # python 2 to 3 compatibility
    - six ==1.15.0

test:
  requires:
    - pip
    - {{ pin_compatible('numpy') }}
    - matplotlib
    - pandas
  commands:
    - pip check
  imports:
    - jupyterlab_plotly
    - plotly
    - plotly.offline
    - plotly.io
    - plotly.matplotlylib
    - plotly.matplotlylib.mplexporter
    - plotly.matplotlylib.mplexporter.renderers
    - plotly.figure_factory
    - plotly.data
    - plotly.colors
    - plotly.express
    - plotly.express.data
    - plotly.express.colors
    - plotly.graph_objects
    - _plotly_utils
    - _plotly_utils.colors
    - _plotly_future_

about:
  home: https://plot.ly/python/
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: An interactive JavaScript-based visualization library for Python
  description: |
    plotly.py is an interactive, open-source, and JavaScript-based graphing
    library for Python. Built on top of plotly.js, plotly.py is a high-level,
    declarative charting library that includes over 30 chart types,
    including scientific charts, 3D graphs, statistical charts, SVG maps,
    financial charts, and more.
  doc_url: https://plot.ly/python/
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - chohner
    - moorepants
    - ocefpaf
