{% set version = "1.12.5" %}
{% set sha256 = "b5a6260626b9b7caafb73e7a54447790337383373b699c3c323a45f32f27f7cd" %}
{% set md5 = "6ee8480c40064a3650940001bd7bbc09" %}

package:
  name: plotly
  version: {{ version }}

source:
  fn: plotly-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/plotly/plotly-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests
    - pytz
    - six

test:
  imports:
    - plotly

about:
  home: https://plot.ly/python/
  license: MIT
  summary: 'An interactive, browser-based graphing library for Python'
  description: |
    Plotly's Python graphing library makes interactive,
    publication-quality graphs online. Examples of how to make line
    plots, scatter plots, area charts, bar charts, error bars, box plots,
    histograms, heatmaps, subplots, multiple-axes, polar charts and
    bubble charts.
  doc_url: https://plot.ly/python/
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - chohner
