travis:
  secure:
    BINSTAR_TOKEN: cf6zy6R8RVVOqHZDjqgsEkGaetklUWnQCXiJKS4C8VpegL88a+cPBZIj14QNfF++zXaeveCcETs7bIb7dceG1lGrkineHqjmJuAfwS8zQdwSwUsVQUf5uDLKcFpvYrOh/aqrEC7y1Qo0vrNXFjvWD1bR70cP7OQWlAFKTox9Yqc+ijtomtA0BuMUUi+f5ODW/5f6U+PtYUksguW5rvj4epHioJjj8s4JTfp5kcIqOd+3Roxh99WhoUczUJUiY+vQoYvuH2DcMhPSv9DQdBwv313g9B1x2EXYc4fDVPVBpxdvpAOf25PX6BB5ar5t83Jxh2TxX+rFil5o3taqZw3kxhOKcVbQmaSSgKH0P/jwv3oigE4zSl0VN4uWb/PoPJq3G66XlXQc0CX84M86ss2mqpD9CNfRMSGVl69n5oV4tzj6OlQtdyL+fG3xocIqOBtw/dJTJy+OEayB8jqSGOsulUog9zFsFkXT6cR+jzrLs5o/RyoNND4Xso/mGoJp/ghFcZt6fYk1y+pN9ryY/AFhSBe10G/mHmD3ZD1xedinx92bU7b7keABipXF1SLjqmdGRETaGNAKPuhm0fb+Pmv/CN2nAj+s8Dp3YRExMYXdVpsyg+uLOINHkdUJuvX64uquB713e6dCuUwuE6GyUh/2mDxmVkFkXqkotZ+NytxRwdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
