travis:
  secure:
    BINSTAR_TOKEN: UEdS/9nMOlf57wIL7R0r0Y3/H9wz5jYsoFusHBJt5aEAo3/lnmZUy33KoM7EW1MOTKfufWFewLGgF8yF65RgbLJNJmihCSRKY2a76RhpQF7I1xV3XU8ioCkPRqFduUZyHF9/HjHFtcoNuDEkRt+PW+XjIGY2cwylItwUjrRgoMXaCGBmlfWKTQooAkyQS5CQwHQ/72nwBkGD3FDRyfRBYtJPvAF7YteeFw/DFteiPKwGX0U+0bScnM3TL0/EAXaLEnZmBEPQDyrC4LGg71vGt0lsoNSs8Tu67q+w5BYQLme3EWTWBDFqQwR8FGpDyIhFAJvPf2RxjP13TBgsPjMvAcHCBflxgYA/9rxAuIt+QI0AvlXEDQRCHcyk5i2nhINh3/Xr4Lsm6X2Z1d3rgTCf3DQP9TFLg/ETKNPZgC5QAkn2KISsQLz4DsWRqZktm87eZZ2YfOCM6nwo5P5ODw12GvRNdzp4g73mwY7cSQ3gEck5AxxjeXoXAtCyfs51gGBIikp7Cr+N73uvC0wGl/A6KZHfLprFKVzLvNm3lZjbU7WihA430SH0cwO/9spx4ZQ6PtHNS0MrjMtqlBUJ1GsaTs+ph20ntD5W3QBe9N+R8zG/e9ctR0SM74ncLIWmLRFGwnkVxY136CAUaOMaEh9n5awzDhK7JDheQnAT3dVkpBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
